### ISSUE TITLE
我爱圆圆

### ISSUE THREAD

**Issue by MichaelHuyp** [lybenson/ts-checker#1]
我是一个冰人 我生冰了

**Comment by lybenson** [comment]
有冰就去制

**Comment by lybenson** [comment]
我很希望你真的是ikun 而不是在这里伪装碟中谍搞反串黑坤坤 爱蔡徐坤不仅仅是爱在短视频发他视频 还要爱他爱在心动的那首歌 爱在为之动容的颜值 爱在每一个爱的瞬间 真爱粉永远都在 不要黑坤坤了 也不要去理会小黑子 坤坤真的很好的 他非常的宠粉 前几天我过生日的时候 坤坤还下了颗蛋给我吃
